
exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('reviews').del()
    .then(function () {
      // Inserts seed entries
      return knex('reviews').insert([
        {id: 1, title: 'Good', user_ID: 2, property_ID: 3, comments: 'Awesome house',pros: 'Big Garden', 
        cons: 'Junk in Garage cannot use for parking', rating: 4, start_of_tenancy: 2015, end_of_tenancy: 2018, helpful_score: 2, img:""},
        {id: 2, title: 'Moldy', user_ID: 1, property_ID: 4, comments: 'No windows open to air out the house',pros: 'Very quiet area', 
        cons: 'No sun in untill late evening ', rating: 2, start_of_tenancy: 2017, end_of_tenancy: 2018, helpful_score: 1, img:""},
        {id: 3, title: 'Sunny', user_ID: 2, property_ID: 2, comments: 'Good house',pros: 'Nice Neighbours', 
        cons: 'No big garden for kids', rating: 3, start_of_tenancy: 2016, end_of_tenancy: 2018, helpful_score: 4, img:""},
        {id: 4, title: 'Very small', user_ID: 4, property_ID: 5, comments: 'House is very small. All bedrooms can only fit a single bed',
        pros: 'Close to public transport',
        cons: 'Neighbours are a nightmare', rating: 2, start_of_tenancy: 2016,end_of_tenancy: 2018, helpful_score: 10, img:""},
        {id: 5, title: 'Love this House', user_ID: 1, property_ID: 1, comments: 'This place this the best',
        pros: 'Big rooms, spa bath, balcony, big garden, fancy kitchen', 
        cons: 'Some work needs to be done on the outside fence', rating: 4, start_of_tenancy: 2017, end_of_tenancy: 2018, helpful_score: 22, img:""},
        {id: 6, title: 'Love this House', user_ID: 1, property_ID: 3, comments: 'This place this the best',
        pros: 'Big rooms, spa bath, balcony, big garden, fancy kitchen', 
        cons: 'Some work needs to be done on the outside fence', rating: 4, start_of_tenancy: 2020, end_of_tenancy: 2020, helpful_score: 22, img:""},
        {id: 7, title: 'Love this House', user_ID: 1, property_ID: 3, comments: 'This place this the best',
        pros: 'Big rooms, spa bath, balcony, big garden, fancy kitchen', 
        cons: 'Some work needs to be done on the outside fence', rating: 4, start_of_tenancy: 2020, end_of_tenancy: 2020, helpful_score: 22, img:""},
        {id: 8, title: 'Love this House', user_ID: 2, property_ID: 1, comments: 'This place this the best',
        pros: 'Big rooms, spa bath, balcony, big garden, fancy kitchen', 
        cons: 'Some work needs to be done on the outside fence', rating: 4, start_of_tenancy: 2020, end_of_tenancy: 2020, helpful_score: 22, img:""},
        {id: 9, title: 'Love this House', user_ID: 3, property_ID: 2, comments: 'This place this the best',
        pros: 'Big rooms, spa bath, balcony, big garden, fancy kitchen', 
        cons: 'Some work needs to be done on the outside fence', rating: 4, start_of_tenancy: 2020, end_of_tenancy: 2020, helpful_score: 22, img:""},
        {id: 10, title: 'Love this House', user_ID: 4, property_ID: 6, comments: 'This place this the best',
        pros: 'Big rooms, spa bath, balcony, big garden, fancy kitchen', 
        cons: 'Some work needs to be done on the outside fence', rating: 4, start_of_tenancy: 2020, end_of_tenancy: 2020, helpful_score: 22, img:""},
        {id: 11, title: 'Neato', user_ID: 6, property_ID: 1, comments: 'I loved how soft the grass is ',
        pros: 'good irrigation', cons: 'wish there were more', rating: 3, start_of_tenancy: 2011, end_of_tenancy: 2013, helpful_score: 2},
        {id: 12, title: 'Open', user_ID: 7, property_ID: 2, comments:'Lots of sun thanks to large windows',
        pros: 'great visibility', cons: 'Old curtains!', rating: 4, start_of_tenancy: 2006, end_of_tenancy:2009, helpful_score:3 },
        {id: 13, title: 'Great Ventilation', user_ID: 8, property_ID: 3, comments: 'Great space under the house for brewing',
        pros: 'Lots of privacy', cons: 'Someone had a fire under the house', rating: 2, start_of_tenancy: 1999, end_of_tenancy: 2002, helpful_score: 3},
        {id: 14, title: 'Hidey Hole', user_ID: 9, property_ID: 4, comments: 'Very private with tall fences, no one knew I was there',
        pros: 'Nice views & no Nissans on the street', cons: 'No Renaults either', rating: 3, start_of_tenancy: 2013,end_of_tenancy: 2013, helpful_score: 4},
        {id: 15, title: 'Weird place', user_ID: 10, property_ID: 5, comments: 'Very strange locals - poorly dressed',
        pros: 'High Ceilings', cons: 'weird flatmates', rating:1 , start_of_tenancy: 2017, end_of_tenancy: 2018, helpful_score: 3},
        {id: 16, title: 'Sunny House', user_ID: 3, property_ID: 2, comments: 'This place is very quiet',
        pros: 'Big rooms, spa bath, balcony, big garden, fancy kitchen', 
        cons: 'Some work needs to be done on the outside fence', rating: 4, start_of_tenancy: 2017, end_of_tenancy: 2018, helpful_score: 22, img:""},
        {id: 17, title: 'Love this House', user_ID: 3, property_ID: 2, comments: 'This place is awesome',
        pros: 'Big rooms, spa bath, balcony, big garden, fancy kitchen', 
        cons: 'Some work needs to be done outside', rating: 4, start_of_tenancy: 2016, end_of_tenancy: 2017, helpful_score: 22, img:""},
        {id: 18, title: 'Great House', user_ID: 3, property_ID: 2, comments: 'This place is awesome',
        pros: 'Big rooms, spa bath, balcony, big garden, fancy kitchen', 
        cons: 'Some work needs to be done outside', rating: 4, start_of_tenancy: 2015, end_of_tenancy: 2016, helpful_score: 22, img:""},
        {id: 19, title: 'Love this House', user_ID: 3, property_ID: 2, comments: 'This place is awesome',
        pros: 'Big rooms, spa bath, balcony, big garden, fancy kitchen', 
        cons: 'Some work needs to be done outside', rating: 4, start_of_tenancy: 2016, end_of_tenancy: 2017, helpful_score: 22, img:""},
        {id: 20, title: 'Nice house', user_ID: 2, property_ID: 3, comments: 'Great house',pros: 'Big Garden, big lounge area, nice kitchen', 
        cons: 'Junk in Garage cannot use for parking', rating: 4, start_of_tenancy: 2015, end_of_tenancy: 2018, helpful_score: 2, img:""},
        {id: 21, title: 'Great house', user_ID: 2, property_ID: 3, comments: 'Awesome house',pros: 'Big Garden, big outside garden for children', 
        cons: 'Some work needs to be done on the outside fence', rating: 4, start_of_tenancy: 2015, end_of_tenancy: 2018, helpful_score: 2, img:""},
        {id: 22, title: 'Amazing House', user_ID: 2, property_ID: 3, comments: 'beautiful garden',
        pros: 'Big rooms with attach bathroom, spa bath, big garden, fancy kitchen', 
        cons: 'This house need to color in inside the house', rating: 4, start_of_tenancy: 2014, end_of_tenancy: 2018, helpful_score: 18, img:""},
        {id: 23, title: 'Good House', user_ID: 2, property_ID: 3, comments: 'Very warm house',
        pros: 'Big rooms, spa bath, big garden, fancy kitchen', 
        cons: 'This house need to color in inside the house', rating: 4, start_of_tenancy: 2015, end_of_tenancy: 2018, helpful_score: 18, img:""},
        {id: 24, title: 'Nice House', user_ID: 1, property_ID: 4, comments: 'Very nice neighbours',pros: 'Very quiet area', 
        cons: 'Rooms are very small', rating: 2, start_of_tenancy: 2016, end_of_tenancy: 2017, helpful_score: 1, img:""},
        {id: 25, title: 'Not To good House', user_ID: 1, property_ID: 4, comments: 'No windows open to air out the house',pros: 'Very quiet place for walking', 
        cons: 'No sun in untill late evening', rating: 2, start_of_tenancy: 2018, end_of_tenancy: 2019, helpful_score: 1, img:""},
        {id: 26, title: 'Moldy', user_ID: 1, property_ID: 4, comments: 'No windows open to air out the house',pros: 'Very quiet area', 
        cons: 'No sun in untill late evening ', rating: 2, start_of_tenancy: 2017, end_of_tenancy: 2018, helpful_score: 1, img:""},
        {id: 27, title: 'Amazing House', user_ID: 2, property_ID: 5, comments: 'Very cool place',
        pros: 'Big rooms, balcony, big garden, fancy kitchen', 
        cons: 'This house need to color in inside the house', rating: 3, start_of_tenancy: 2017, end_of_tenancy: 2020, helpful_score: 18, img:""},
        {id: 28, title: 'Good House', user_ID: 2, property_ID: 5, comments: 'Very warm house',
        pros: 'Big rooms, spa bath, big garden, fancy kitchen', 
        cons: 'This house need to color in inside the house', rating: 4, start_of_tenancy: 2015, end_of_tenancy: 2018, helpful_score: 18, img:""},
        {id: 29, title: 'Nice House', user_ID: 2, property_ID: 5, comments: 'Very quit place',
        pros: 'Big rooms, spa bath, big garden, fancy kitchen, big bathroom', 
        cons: 'This house need to color in inside the house', rating: 4, start_of_tenancy: 2015, end_of_tenancy: 2018, helpful_score: 18, img:""},
        {id: 30, title: 'Amazing House', user_ID: 2, property_ID: 5, comments: 'beautiful garden',
        pros: 'Big rooms with attach bathroom, spa bath, big garden, fancy kitchen', 
        cons: 'This house need to color in inside the house', rating: 4, start_of_tenancy: 2014, end_of_tenancy: 2018, helpful_score: 18, img:""},
        {id: 31, title: 'Beautiful House', user_ID: 3, property_ID: 6, comments: 'Nice neighbours',
        pros: 'Big rooms,renovated kitchen, big lounge', 
        cons: 'This house need to be done outside fence', rating: 4, start_of_tenancy: 2012, end_of_tenancy: 2014, helpful_score: 19, img:""},
        {id: 32, title: 'Sunny House', user_ID: 3, property_ID: 6, comments: 'This place is very quiet',
        pros: 'Big rooms, spa bath, balcony, big garden, fancy kitchen', 
        cons: 'Some work needs to be done on the outside fence', rating: 4, start_of_tenancy: 2017, end_of_tenancy: 2018, helpful_score: 22, img:""},
        {id: 33, title: 'Love this House', user_ID: 3, property_ID: 6, comments: 'This place is awesome',
        pros: 'Big rooms, spa bath, balcony, big garden, fancy kitchen', 
        cons: 'Some work needs to be done outside', rating: 4, start_of_tenancy: 2016, end_of_tenancy: 2017, helpful_score: 22, img:""},
        {id: 34, title: 'Great House', user_ID: 3, property_ID: 6, comments: 'This place is awesome',
        pros: 'Big rooms, spa bath, balcony, big garden, fancy kitchen', 
        cons: 'Some work needs to be done outside', rating: 4, start_of_tenancy: 2015, end_of_tenancy: 2016, helpful_score: 22, img:""},
        {id: 35, title: 'Love this House', user_ID: 3, property_ID: 6, comments: 'This place is awesome',
        pros: 'Big rooms, spa bath, balcony, big garden, fancy kitchen', 
        cons: 'Some work needs to be done outside', rating: 4, start_of_tenancy: 2016, end_of_tenancy: 2017, helpful_score: 22, img:""},
        {id: 36, title: 'Beautiful House', user_ID: 3, property_ID: 7, comments: 'Nice neighbours',
        pros: 'Big rooms,renovated kitchen, big lounge', 
        cons: 'This house need to be done outside fence', rating: 4, start_of_tenancy: 2012, end_of_tenancy: 2014, helpful_score: 19, img:""},
        {id: 37, title: 'Sunny House', user_ID: 3, property_ID: 7, comments: 'This place is very quiet',
        pros: 'Big rooms, spa bath, balcony, big garden, fancy kitchen', 
        cons: 'Some work needs to be done on the outside fence', rating: 4, start_of_tenancy: 2017, end_of_tenancy: 2018, helpful_score: 22, img:""},
        {id: 38, title: 'Love this House', user_ID: 3, property_ID: 7, comments: 'This place is awesome',
        pros: 'Big rooms, spa bath, balcony, big garden, fancy kitchen', 
        cons: 'Some work needs to be done outside', rating: 4, start_of_tenancy: 2016, end_of_tenancy: 2017, helpful_score: 22, img:""},
        {id: 39, title: 'Great House', user_ID: 3, property_ID: 7, comments: 'This place is awesome',
        pros: 'Big rooms, spa bath, balcony, big garden, fancy kitchen', 
        cons: 'Some work needs to be done outside', rating: 4, start_of_tenancy: 2015, end_of_tenancy: 2016, helpful_score: 22, img:""},
        {id: 40, title: 'Love this House', user_ID: 3, property_ID: 7, comments: 'This place is awesome',
        pros: 'Big rooms, spa bath, balcony, big garden, fancy kitchen', 
        cons: 'Some work needs to be done outside', rating: 4, start_of_tenancy: 2016, end_of_tenancy: 2017, helpful_score: 22, img:""},
        {id: 41, title: 'Beautiful House', user_ID: 3, property_ID: 7, comments: 'Nice neighbours',
        pros: 'Big rooms,renovated kitchen, big lounge', 
        cons: 'This house need to be done outside fence', rating: 4, start_of_tenancy: 2012, end_of_tenancy: 2014, helpful_score: 19, img:""},
        {id: 42, title: 'Sunny House', user_ID: 3, property_ID: 8, comments: 'This place is very quiet',
        pros: 'Big rooms, spa bath, balcony, big garden, fancy kitchen', 
        cons: 'Some work needs to be done on the outside fence', rating: 4, start_of_tenancy: 2017, end_of_tenancy: 2018, helpful_score: 22, img:""},
        {id: 43, title: 'Love this House', user_ID: 3, property_ID: 8, comments: 'This place is awesome',
        pros: 'Big rooms, spa bath, balcony, big garden, fancy kitchen', 
        cons: 'Some work needs to be done outside', rating: 4, start_of_tenancy: 2016, end_of_tenancy: 2017, helpful_score: 22, img:""},
        {id: 44, title: 'Great House', user_ID: 3, property_ID: 8, comments: 'This place is awesome',
        pros: 'Big rooms, spa bath, balcony, big garden, fancy kitchen', 
        cons: 'Some work needs to be done outside', rating: 4, start_of_tenancy: 2015, end_of_tenancy: 2016, helpful_score: 22, img:""},
        {id: 45, title: 'Love this House', user_ID: 3, property_ID: 8, comments: 'This place is awesome',
        pros: 'Big rooms, spa bath, balcony, big garden, fancy kitchen', 
        cons: 'Some work needs to be done outside', rating: 4, start_of_tenancy: 2016, end_of_tenancy: 2017, helpful_score: 22, img:""},
        {id: 46, title: 'Beautiful House', user_ID: 3, property_ID: 9, comments: 'Nice neighbours',
        pros: 'Big rooms,renovated kitchen, big lounge', 
        cons: 'This house need to be done outside fence', rating: 4, start_of_tenancy: 2012, end_of_tenancy: 2014, helpful_score: 19, img:""},
        {id: 47, title: 'Sunny House', user_ID: 3, property_ID: 9, comments: 'This place is very quiet',
        pros: 'Big rooms, spa bath, balcony, big garden, fancy kitchen', 
        cons: 'Some work needs to be done on the outside fence', rating: 4, start_of_tenancy: 2017, end_of_tenancy: 2018, helpful_score: 22, img:""},
        {id: 48, title: 'Love this House', user_ID: 3, property_ID: 9, comments: 'This place is awesome',
        pros: 'Big rooms, spa bath, balcony, big garden, fancy kitchen', 
        cons: 'Some work needs to be done outside', rating: 4, start_of_tenancy: 2016, end_of_tenancy: 2017, helpful_score: 22, img:""},
        {id: 49, title: 'Great House', user_ID: 3, property_ID: 9, comments: 'This place is awesome',
        pros: 'Big rooms, spa bath, balcony, big garden, fancy kitchen', 
        cons: 'Some work needs to be done outside', rating: 4, start_of_tenancy: 2015, end_of_tenancy: 2016, helpful_score: 22, img:""},
        {id: 50, title: 'Love this House', user_ID: 3, property_ID: 9, comments: 'This place is awesome',
        pros: 'Big rooms, spa bath, balcony, big garden, fancy kitchen', 
        cons: 'Some work needs to be done outside', rating: 4, start_of_tenancy: 2016, end_of_tenancy: 2017, helpful_score: 22, img:""},
        {id: 51, title: 'Beautiful House', user_ID: 3, property_ID: 10, comments: 'Nice neighbours',
        pros: 'Big rooms,renovated kitchen, big lounge', 
        cons: 'This house need to be done outside fence', rating: 4, start_of_tenancy: 2012, end_of_tenancy: 2014, helpful_score: 19, img:""},
        {id: 52, title: 'Sunny House', user_ID: 3, property_ID: 10, comments: 'This place is very quiet',
        pros: 'Big rooms, spa bath, balcony, big garden, fancy kitchen', 
        cons: 'Some work needs to be done on the outside fence', rating: 4, start_of_tenancy: 2017, end_of_tenancy: 2018, helpful_score: 22, img:""},
        {id: 53, title: 'Love this House', user_ID: 3, property_ID: 10, comments: 'This place is awesome',
        pros: 'Big rooms, spa bath, balcony, big garden, fancy kitchen', 
        cons: 'Some work needs to be done outside', rating: 4, start_of_tenancy: 2016, end_of_tenancy: 2017, helpful_score: 22, img:""},
        {id: 54, title: 'Great House', user_ID: 3, property_ID: 10, comments: 'This place is awesome',
        pros: 'Big rooms, spa bath, balcony, big garden, fancy kitchen', 
        cons: 'Some work needs to be done outside', rating: 4, start_of_tenancy: 2015, end_of_tenancy: 2016, helpful_score: 22, img:""},
        {id: 55, title: 'Love this House', user_ID: 3, property_ID: 10, comments: 'This place is awesome',
        pros: 'Big rooms, spa bath, balcony, big garden, fancy kitchen', 
        cons: 'Some work needs to be done outside', rating: 4, start_of_tenancy: 2016, end_of_tenancy: 2017, helpful_score: 22, img:""},
      ]);
    });
};
